"""Regenerate snapshot.md — a combined-docs dump for pasting into another AI chat/tool.

Usage: python -m scripts.make_snapshot
"""
import datetime
from pathlib import Path

from app.config import BASE_DIR

SOURCE_FILES = [
    "README.md",
    "DEVELOPMENT.md",
    "CLAUDE.md",
    "ARCHITECTURE.md",
    "IDEAS.md",
    "IMPLEMENTATION_HISTORY.md",
]

OUTPUT_FILE = "snapshot.md"


def main() -> None:
    today = datetime.date.today().isoformat()
    sections = [
        f"# Budget App — Combined Documentation Snapshot\n\n"
        f"_Auto-generated by `scripts/make_snapshot.py` from {', '.join(SOURCE_FILES)} "
        f"as of {today} — for pasting into another chat/tool for review. "
        f"MAKING_PUBLIC.md and security-audit.md are deliberately excluded (the former "
        f"is about this repo's own visibility, not the app itself; the latter is "
        f"written for a Claude instance running on the VPS, not for pasting elsewhere). "
        f"Regenerate rather than hand-edit — this file "
        f"is a derived view, not a source of truth; the individual .md files are._\n"
    ]

    for i, filename in enumerate(SOURCE_FILES, start=1):
        content = (BASE_DIR / filename).read_text()
        sections.append(f"---\n\n# {i}. {filename}\n\n{content.strip()}\n")

    Path(BASE_DIR / OUTPUT_FILE).write_text("\n".join(sections))
    print(f"Wrote {OUTPUT_FILE} from {len(SOURCE_FILES)} source files.")


if __name__ == "__main__":
    main()
